### PR TITLE
Update CSS Snippets section

### PR DESCRIPTION
**Pull request by konhi**
Issue: #29 

- [x] update terminology (`snippets` instead `tweaks`, `obsidian.css` is no more)
- [x] adds other links related to snippets (feel free to add more if there are any)
- [x] update current snippets to new style
- [x] add examples
- [ ] #34 
- [ ] verify if links and metadata are correct

@kmaasrud what do you think about current update? Feel free to suggest any changes. Please let me know if:
- style in README.md is okay and I can continue updating styles like that
- style of .css file is okay (I formatted it and added metadata)
- structure of files is fine

### CODE REVIEW

**Comment by konhi** [comment]
image

**Comment by kmaasrud** [comment]
Oops, didn't mean to mark this as ready for review... But no mind, I think that style looks very good, and I like how you've structured the directories :+1:

Very much approved 😄

**Comment by konhi** [comment]
That's so cool! By the way, latest [Andy Matuschak mode is a plugin](https://github.com/deathau/sliding-panes-obsidian), so I'm gonna remove it from snippets.

**Comment by kmaasrud** [comment]
> That's so cool! By the way, latest [Andy Matuschak mode is a plugin](https://github.com/deathau/sliding-panes-obsidian), so I'm gonna remove it from snippets.

Perfect!

**Comment by konhi** [comment]
Actually this style causes problem with id of header, for example:

`## Outliner For The Outline and File Explorer by @Shamama & @wonton`
causes `id` to be very long:
`outliner-for-the-outline-and-file-explorer-by-shamama--wonton`

I think it's better to move author out of heading.

**Comment by konhi** [comment]
@kmaasrud could you please check if `Collapsing Sidebar` works? I'm not sure if this is desired result 😅
collapse

**Comment by kmaasrud** [comment]
> @kmaasrud could you please check if `Collapsing Sidebar` works? I'm not sure if this is desired result 😅

I don't have my computer at the ready right now, but I fear it might not work, yes... I think I made that CSS snippet, and it was some while ago. They've probably changed the DOM structure since then...

I'll open a separate issue on it, and have it fixed once this PR is done 👍 You can just leave it without an example GIF for now 😊

**Comment by konhi** [comment]
`task-list-preview-relationship-line-correction.css` supposed to fix this unaligement between checkboxes and list:

image

I think it got fixed by developers. This is how it looks now **without any snippets.**

image

Therefore, I'm removing this snippet.

**Comment by konhi** [comment]
@kmaasrud Examples done!

**Comment by kmaasrud** [comment]
God damn, amazing work! Thank you so much for your contribution 😊

**Pull request merged**
