### PR TITLE
Add folder emojis

### PR DESCRIPTION
**Pull request by ScottKillen**
Add css snippet for adding emojis to **specific** folders in the explorer view

### CODE REVIEW

**Comment by kmaasrud** [comment]
Thanks for the PR! I will include this snippet ASAP, but I'm reconsidering how I want to present the snippets in the list, so I'll wait until I've got that figured out 😄

**Comment by ScottKillen** [comment]
Sounds good! 

-- 
Scott Killen

On August 19, 2021, GitHub ***@***.***> wrote:
> Thanks for the PR! I will include this snippet ASAP, but I'm
> reconsidering how I want to present the snippets in the list, so I'll
> wait until I've got that figured out 😄
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kmaasrud/awesome-obsidian/pull/28#issuecomment-
902499128>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AALQUZP2X3U4ICPAPEXC2N3T5YBBHANCNFSM5CI7L4JA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-
email>.

**Comment by konhi** [comment]
@ScottKillen thanks for contributing this cool snippet!
I'm afraid that the commit changes whole README file, probably because of using autoformatting. Could you please fix that? 😊

**Comment by kmaasrud** [comment]
@konhi we could probably just copy over his snippet manually as part of redoing the other snippets. He's got quite a nice example image as well :smile:

**Comment by konhi** [comment]
@ScottKillen new presentation of snippets is done, could you please change your commit accordingly to how it looks now? Or I could also do the commit for you, if you prefer! 😊

**Comment by ScottKillen** [comment]
All done!

**Comment by kmaasrud** [comment]
Exactly according to style, this is great! Thanks for the contribution :smile:

**Pull request merged**
