### PR TITLE
Add every Community Theme

### PR DESCRIPTION
**Pull request by konhi**
- [ ] decide if this section (or others) should be foldable due to high length

### CODE REVIEW

**Comment by kmaasrud** [comment]
Aaah, you're a genius for suggesting folding sections!! Let's merge this PR first, then I'll wrap all sections in `<detail>`

**Comment by konhi** [comment]
I occured one problem. We discussed that it would be best if we keep a description of a theme. But it seem to be unworthy to do, as many themes lack of it in the original repository.
Therefore I suggest removing the description field. L
Also, we could possibly remove credits field and change name field to repository (`author/repository-name`), so it's gonna be maximally compact.
Or else, we could do it another way, without the table. Let me know what do you think!

**Comment by kmaasrud** [comment]
No I like those two ideas! Go with the compact version 👍

**Comment by konhi** [comment]
@kmaasrud let me know if it looks as intended!

**Comment by kmaasrud** [comment]
This looks all good! Once again, thank you so much for all your work 😍

**Pull request merged**
